version: '3'                                                                                          docker-compose.ymlversion: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MARIADB_ROOT_PASSWORD
    env_file:
      - db.env

  app:
    container_name: app-server
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /mnt/storagedisk/docker-nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '8000'
      - '8080'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  web:
    build: ./web
    restart: always
    volumes:
      - /mnt/storagedisk/docker-nextcloud/nextcloud:/var/www/html
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    environment:
      - VIRTUAL_HOST=YOURHOST.COM
      - LETSENCRYPT_HOST=YOURHOST.COM
      - LETSENCRYPT_EMAIL=YOUREMAIL@EMAIL.COM
    depends_on:
      - app
      - onlyoffice-document-server
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8000:8000
      - 8080:8080
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  certs:
  vhost.d:
  html:
  document_data:
  document_log:

networks:
  proxy-tier:
